[package]
name = "engine"
version = "0.1.0"
authors = ["Andy Yu <andyyu2004@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
error = { path = "../error" }
parse = { path = "../parse" }
salsa = "0.16.0"
ena = "0.14"
